services:
- type: web
  name: wordpress
  env: docker
  plan: standard
  autoDeploy: false
  disk:
    name: wordpress
    mountPath: /var/www/html
    sizeGB: 20
  envVars:
  - key: WORDPRESS_DB_HOST
    fromService:
      name: mysql-wordpress
      type: pserv
      property: host
  - key: WORDPRESS_DB_NAME
    fromService:
      name: mysql-wordpress
      type: pserv
      envVarKey: MYSQL_DATABASE
  - key: WORDPRESS_DB_USER
    fromService:
      name: mysql-wordpress
      type: pserv
      envVarKey: MYSQL_USER
  - key: WORDPRESS_DB_PORT
    fromService:
      name: mysql-wordpress
      type: pserv
      envVarKey: MYSQL_PORT
  - key: WORDPRESS_DB_PASSWORD
    fromService:
      name: mysql-wordpress
      type: pserv
      envVarKey: MYSQL_PASSWORD
 
